{{ $chartName := .Chart.Name }}
{{ $dot := . }}
{{- range $replica := $.Values.replicas }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $dot.Release.Name }}-{{ $replica }}
  labels:
    app.kubernetes.io/name: {{ $dot.Release.Name }}
spec:
  containers:
  - name: main
    image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
{{- end }}
